# site settings
title: Readme Careers
subtitle: Offer Negotiation Coaching
email: readmecareers@gmail.com
description: I will provide you with the tools and coaching to confidently navigate job offers and negotiations for an optimal outcome.
baseurl: "" # the subpath of your site, e.g. /blog
url:
author:
street_address:
city: San Francisco
state: CA
zip_code: 94103
country: United States of America
phone: (413)341-4157

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/readmecareers

# build settings
markdown: kramdown

sass:
  style: compressed
